server:
  port: 8081

application:
  service-names:
    "[AUTHENTICATION]": auth-service
    "[USER]": user-service
  open-endpoints:
    - /auth/token

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# For service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: lb://${application.service-names.[AUTHENTICATION]}
          predicates:
            - Path=/auth/**

